/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package clases;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class INTERFAZ_JPanelZona extends javax.swing.JPanel {
    LD_NormalZona A = new LD_NormalZona();

    /**
     * Creates new form ZonaX
     */
    
    
    public INTERFAZ_JPanelZona() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pantalla_interfaz = new javax.swing.JTable();
        botonLlenas = new javax.swing.JButton();
        botonMostrar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        panelZonas = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pantalla_interfaz.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(pantalla_interfaz);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 739, -1));

        botonLlenas.setBackground(new java.awt.Color(0, 103, 105));
        botonLlenas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botonLlenas.setText("llenar");
        botonLlenas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLlenasActionPerformed(evt);
            }
        });
        jPanel1.add(botonLlenas, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 570, -1, -1));

        botonMostrar.setBackground(new java.awt.Color(0, 103, 105));
        botonMostrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botonMostrar.setText("mostrar");
        botonMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMostrarActionPerformed(evt);
            }
        });
        jPanel1.add(botonMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 570, -1, -1));

        panelZonas.setColumns(20);
        panelZonas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        panelZonas.setRows(5);
        panelZonas.setText("Zona Mira Flores (909M)\nZona Villa Fatima (404C)\nZona Alto Obrajes (111P)\nZona 14 de Septiembre (767C)\nZona Bajo Tejar (818S)\nZona San Antonio (969S)");
        jScrollPane2.setViewportView(panelZonas);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 355, 99));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Zonas registradas:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 162, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Vias:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 79, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 620));
    }// </editor-fold>//GEN-END:initComponents

    private void botonLlenasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLlenasActionPerformed
        A.llenar();
        JOptionPane.showMessageDialog(null, "Llenado exitoso.");
    }//GEN-LAST:event_botonLlenasActionPerformed

    private void botonMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarActionPerformed
        String titulos[] = {"Nombre", "Tipo", "Ubicacion", "Estado", "Longitud", "Num.Carriles", "Num. Semaforos", "Num. Autos"};        
        DefaultTableModel pantalla = new DefaultTableModel(null, titulos);
        LD_NormalZona aux1 = new LD_NormalZona();
        LD_NormalVia aux2 = new LD_NormalVia();
        while(!A.esVacia()){
            NodoZona zx = A.eliFinal();
            while(!zx.getZ().getR().esVacia()){
                NodoVia vx = zx.getZ().getR().eliFinal();
                String fila[] = {vx.getX().getNombre(), vx.getX().getTipo(), vx.getX().getUbicacion(), vx.getX().getEstado(), Integer.toString(vx.getX().getLongitud()), Integer.toString(vx.getX().getNum_carriles()), Integer.toString(vx.getX().getX().nroElem()), Integer.toString(vx.getX().getY().nroElem())};
                pantalla.addRow(fila);
                aux2.adiFinal(vx.getX());
            }
            aux1.adiFinal(zx.getZ());
            zx.getZ().getR().setP(aux2.getP());
            aux2.setP(null);
        }                     
        A.setP(aux1.getP());
        aux1.setP(null);
        pantalla_interfaz.setModel(pantalla);
        
    }//GEN-LAST:event_botonMostrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonLlenas;
    private javax.swing.JButton botonMostrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea panelZonas;
    private javax.swing.JTable pantalla_interfaz;
    // End of variables declaration//GEN-END:variables
}
