/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Ventanas;
import clases.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author ASUS
 */
public class INTERFAZ_JPanelOpcionesDes extends javax.swing.JPanel {
    LD_NormalZona A = new LD_NormalZona();
    //ColaCircularSemaforo S = new ColaCircularSemaforo();
    /**
     * Creates new form INTERFAZ_JPanelOpcionesDes
     */
    public INTERFAZ_JPanelOpcionesDes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jPanel1 = new javax.swing.JPanel();
        botonMostrar = new javax.swing.JButton();
        leerVia = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pantalla_interfaz = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        pantalla_interfaz_2 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonMostrar.setBackground(new java.awt.Color(0, 103, 105));
        botonMostrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botonMostrar.setText("Mostrar");
        botonMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMostrarActionPerformed(evt);
            }
        });
        jPanel1.add(botonMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, -1, -1));

        leerVia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        leerVia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leerViaActionPerformed(evt);
            }
        });
        jPanel1.add(leerVia, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 210, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Ingrese via:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        jScrollPane1.setViewportView(pantalla_interfaz);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, -1, 160));

        jScrollPane2.setViewportView(pantalla_interfaz_2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, -1, 140));

        jPanel2.setBackground(new java.awt.Color(64, 165, 120));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 30)); // NOI18N
        jLabel1.setText("Cambiar el tiempo del semaforo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addContainerGap(295, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, -1));

        jPanel3.setBackground(new java.awt.Color(64, 165, 120));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 780, 60));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Antes:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Despues:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarActionPerformed
        // TODO add your handling code here:
        try {
            A.llenar();
            String titulos[] = {"Color","Duracion"};
            DefaultTableModel pantalla = new DefaultTableModel(null, titulos);
            DefaultTableModel pantalla2 = new DefaultTableModel(null, titulos);        

            LD_NormalZona aux1 = new LD_NormalZona();
            LD_NormalVia aux2 = new LD_NormalVia();
            ColaCircularSemaforo auxSem = new ColaCircularSemaforo();
            ColaCircularSemaforo aux = new ColaCircularSemaforo();
            String via = leerVia.getText();

            while(!A.esVacia()){            
                NodoZona zx = A.eliFinal();                        
                while(!zx.getZ().getR().esVacia()){                    
                    NodoVia vx = zx.getZ().getR().eliFinal();
                    if(vx.getX().getNombre().equals(via)){
                        while(!vx.getX().getX().esVacia()){
                            Semaforo sx = vx.getX().getX().eli();
                            String fila2[] = {sx.getColor(),Integer.toString(sx.getDuracion())};
                            pantalla2.addRow(fila2);
                            sx.setDuracion(60);
                            auxSem.adi(sx);
                        }
                        vx.getX().getX().vaciar(auxSem);
                        while(!vx.getX().getX().esVacia()) {
                            Semaforo elem = vx.getX().getX().eli();
                            String fila[] = {elem.getColor(),Integer.toString(elem.getDuracion())};
                            pantalla.addRow(fila);
                            aux.adi(elem);
                        }
                        vx.getX().getX().vaciar(aux); 
                    }
                    aux2.adiFinal(vx.getX());
                }
                zx.getZ().getR().setP(aux2.getP());
                aux2.setP(null); 

                aux1.adiFinal(zx.getZ());
            }
            A.setP(aux1.getP());
            aux1.setP(null);
            pantalla_interfaz.setModel(pantalla);
            pantalla_interfaz_2.setModel(pantalla2);
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Dato invalido!!!");
        }
        leerVia.setText("");                
    }//GEN-LAST:event_botonMostrarActionPerformed

    private void leerViaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leerViaActionPerformed
        
    }//GEN-LAST:event_leerViaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonMostrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField leerVia;
    private javax.swing.JTable pantalla_interfaz;
    private javax.swing.JTable pantalla_interfaz_2;
    // End of variables declaration//GEN-END:variables
}
