/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package clases;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class INTERFAZ_JPanelCircularMatricula extends javax.swing.JPanel {
    LD_NormalZona A = new LD_NormalZona();
    /**
     * Creates new form INTERFAZ_JPanelCircularMatricula
     */
    public INTERFAZ_JPanelCircularMatricula() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        botonLeer = new javax.swing.JTextField();
        botonVerificarMatricula = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAutos = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Ingrese el día:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 151, -1, -1));

        botonLeer.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonLeer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLeerActionPerformed(evt);
            }
        });
        jPanel1.add(botonLeer, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 188, 191, 43));

        botonVerificarMatricula.setBackground(new java.awt.Color(0, 103, 105));
        botonVerificarMatricula.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botonVerificarMatricula.setText("Verificar");
        botonVerificarMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerificarMatriculaActionPerformed(evt);
            }
        });
        jPanel1.add(botonVerificarMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 267, 139, 34));

        tablaAutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaAutos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, -1, -1));

        jPanel2.setBackground(new java.awt.Color(64, 165, 120));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 30)); // NOI18N
        jLabel1.setText("Circulacion por 1er digito de la matricula");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 799, -1));

        jPanel3.setBackground(new java.awt.Color(64, 165, 120));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 74, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 546, 799, -1));

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setText("Lunes - 0 y1\nMartes - 2 y 3\nMiercoles - 4 y 5\nJueves - 6 y 7\nViernes - 8 y 9\nSabado y domingo - LIBRE");
        jScrollPane3.setViewportView(jTextArea2);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 230, 180));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void botonLeerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLeerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonLeerActionPerformed

    private void botonVerificarMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerificarMatriculaActionPerformed
        // TODO add your handling code here:
        A.llenar();
        String titulos[] = {"Matricula", "Modelo", "Tipo", "Velocidad"};
        DefaultTableModel pantalla = new DefaultTableModel(null, titulos);
        try {
            String x = botonLeer.getText();
            LD_NormalZona zaux = new LD_NormalZona();
            LD_NormalVia vaux = new LD_NormalVia();
            ColaCircularAuto aaux = new ColaCircularAuto();
            List<String> repetidas = new ArrayList<>();
            while (!A.esVacia()) {
                NodoZona zx = A.eliFinal();            
                while (!zx.getZ().getR().esVacia()) {
                    NodoVia vx = zx.getZ().getR().eliFinal();                
                    while (!vx.getX().getY().esVacia()) {
                        Auto ax = vx.getX().getY().eli();                    
                        char primerDigito = ax.getMatricula().charAt(0);                   
                        boolean sw = false;
                        if (x.equals("Lunes") && (primerDigito == '0' || primerDigito == '1'))
                            sw = true;
                        else if (x.equals("Martes") && (primerDigito == '2' || primerDigito == '3'))
                            sw = true;
                        else if (x.equals("Miercoles") && (primerDigito == '4' || primerDigito == '5'))
                            sw = true;
                        else if (x.equals("Jueves") && (primerDigito == '6' || primerDigito == '7'))
                            sw = true;
                        else if (x.equals("Viernes") && (primerDigito == '8' || primerDigito == '9'))
                            sw = true;
                        else if (x.equals("Sabado") || x.equals("Domingo")) {
                            JOptionPane.showMessageDialog(null,"Dia libre.");
                            botonLeer.setText("");
                            return;
                        }
                        if (sw && !repetidas.contains(ax.getMatricula())) {                                 
                            String fila[] = {ax.getMatricula(), ax.getModelo(), ax.getTipo(), Integer.toString(ax.getVelocidad())};
                            pantalla.addRow(fila);
                            repetidas.add(ax.getMatricula());
                        }
                        aaux.adi(ax);
                    }
                    vaux.adiFinal(vx.getX());
                    vx.getX().getY().vaciar(aaux);
                }            
                zaux.adiFinal(zx.getZ());
                zx.getZ().getR().setP(vaux.getP());
                vaux.setP(null);
            }
            A.setP(zaux.getP());
            zaux.setP(null);
            tablaAutos.setModel(pantalla);
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Dato invalido!!!");
        }                    
    }//GEN-LAST:event_botonVerificarMatriculaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField botonLeer;
    private javax.swing.JButton botonVerificarMatricula;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTable tablaAutos;
    // End of variables declaration//GEN-END:variables
}
