/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Ventanas;

import clases.LD_NormalVia;
import clases.LD_NormalZona;
import clases.NodoVia;
import clases.NodoZona;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class INTERFAZ_JPanelViasConges extends javax.swing.JPanel {
    LD_NormalZona A = new LD_NormalZona();

    /**
     * Creates new form INTERFAZ_JPanelViasConges
     */
    public INTERFAZ_JPanelViasConges() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        leerZona = new javax.swing.JTextField();
        leerVia = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(64, 165, 120));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 30)); // NOI18N
        jLabel2.setText("Vias congestionadas");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addContainerGap(469, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel2)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, -1));

        jPanel3.setBackground(new java.awt.Color(64, 165, 120));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 780, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/NAZ_162c662c0fd84367b892feab0e8db591.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 330, 370));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Ingrese zona:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Ingrese Calle/Avenida:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, -1, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("Verificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, -1, -1));

        leerZona.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        leerZona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leerZonaActionPerformed(evt);
            }
        });
        jPanel1.add(leerZona, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 240, 40));

        leerVia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(leerVia, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 240, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
        String zona = leerZona.getText();
        String via = leerVia.getText();
        boolean sw = false;
        LD_NormalZona aux1 = new LD_NormalZona();
        LD_NormalVia aux2 = new LD_NormalVia();
        while(!A.esVacia()){            
            NodoZona zx = A.eliFinal();
            if(zx.getZ().getNombre().equals(zona)){                
                while(!zx.getZ().getR().esVacia()){
                    NodoVia vx = zx.getZ().getR().eliFinal();
                    if(vx.getX().getNombre().equals(via) && vx.getX().getEstado().equals("Congestionado"))
                        sw = true;
                    aux2.adiFinal(vx.getX());
                }
                zx.getZ().getR().setP(aux2.getP());
                aux2.setP(null);                
            }
            aux1.adiFinal(zx.getZ());
        }
        A.setP(aux1.getP());
        aux1.setP(null);
        if(sw)
            JOptionPane.showMessageDialog(null,"La via: "+via+" de la Zona:"+zona+" esta Congestionada");
         else
            JOptionPane.showMessageDialog(null,"La via: "+via+" de la Zona:"+zona+" esta Descongestionada");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Dato invalido!!!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void leerZonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leerZonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_leerZonaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField leerVia;
    private javax.swing.JTextField leerZona;
    // End of variables declaration//GEN-END:variables
}
