/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package clases;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class INTERFAZ_JPanelMostrarVia extends javax.swing.JPanel {
    LD_NormalZona A = new LD_NormalZona();
    /**
     * Creates new form INTERFAZ_JPanel2
     */
    public INTERFAZ_JPanelMostrarVia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        leerZona = new javax.swing.JTextField();
        botonVerificar = new javax.swing.JButton();
        botonLeer = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        pantalla_interfaz = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(64, 165, 120));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Ingrese Zona:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 129, -1));

        leerZona.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        leerZona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leerZonaActionPerformed(evt);
            }
        });
        jPanel1.add(leerZona, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 190, 40));

        botonVerificar.setBackground(new java.awt.Color(0, 103, 105));
        botonVerificar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botonVerificar.setText("Verificar");
        botonVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerificarActionPerformed(evt);
            }
        });
        jPanel1.add(botonVerificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, -1, -1));

        botonLeer.setBackground(new java.awt.Color(0, 103, 105));
        botonLeer.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botonLeer.setText("Cargar");
        botonLeer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLeerActionPerformed(evt);
            }
        });
        jPanel1.add(botonLeer, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 97, 31));

        jScrollPane1.setViewportView(pantalla_interfaz);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 387, 131));

        jPanel2.setBackground(new java.awt.Color(64, 165, 120));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 30)); // NOI18N
        jLabel1.setText("Vias con doble ruta");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(353, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 110));

        jPanel3.setBackground(new java.awt.Color(64, 165, 120));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 780, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/5172_.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, 300, 310));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void botonVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerificarActionPerformed
        // TODO add your handling code here:
        
            String titulos[] = {"Via"};
            DefaultTableModel pantalla = new DefaultTableModel(null, titulos);
            String zona = leerZona.getText();
            NodoZona R = A.getP();
         while(R.getSig() != null){
             
            if(R.getZ().getNombre().equals(zona)){
                NodoVia S= R.getZ().getR().getP();
                while(S.getSig() != null){
                    if(S.getX().getNombre().equals("Villa Lobos") || S.getX().getNombre().equals("Potosi")){
                        //System.out.println("malll");
                    }
                    else{
                        String fila[] = {S.getX().getNombre()};
                        pantalla.addRow(fila);           
                    }
                    S = S.getSig();
                        
                }
                 
            }
            R = R.getSig();
             
         }
         pantalla_interfaz.setModel(pantalla);
        
    }//GEN-LAST:event_botonVerificarActionPerformed

    private void botonLeerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLeerActionPerformed
        // TODO add your handling code here:
        A.llenar();
         JOptionPane.showMessageDialog(null, "Llenado exitoso.");
    }//GEN-LAST:event_botonLeerActionPerformed

    private void leerZonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leerZonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_leerZonaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonLeer;
    private javax.swing.JButton botonVerificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField leerZona;
    private javax.swing.JTable pantalla_interfaz;
    // End of variables declaration//GEN-END:variables
}
